name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v4.1.0.post0
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        targets: |
            challenge.yml
            requirements.yml
        override-deps: |
          ansible==2.9
